web:
  build: .
  working_dir: /data
  command: python app.py
  links:
    - db
  volumes:
    - .:/data
  ports:
    - "5000:5000"

db:
  image: postgres:13
  ports:
      - 5432:5432
  environment:
      - POSTGRES_USER=ac03
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=products